targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          type_overrides:
            DateTime:
              name: DateTime
            FetchPolicy:
              name: FetchPolicy
      gql_build|ast_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: client_mobile|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:client_mobile/graphql/serializers/date_time_serializer.dart"
              name: DateTimeSerializer
            - import: "package:client_mobile/graphql/serializers/fetch_policy_serializer.dart"
              # Can be removed when http://bit.ly/3lBbycE is resolved
              name: FetchPolicySerializer
      gql_build|data_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client_mobile|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            FetchPolicy:
              name: FetchPolicy
      gql_build|var_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client_mobile|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            FetchPolicy:
              name: FetchPolicy

      ferry_generator|req_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client_mobile|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            FetchPolicy:
              name: FetchPolicy

      json_serializable_immutable_collections:
        # configure your options here, same as json_serializable
        options:
          explicit_to_json: true
      json_serializable:json_serializable:
        generate_for:
          # exclude everything to avoid conflicts, this library uses a custom builder
          include:
          exclude:
            - test/**
            - lib/**
